# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        name: black
        entry: black
        types: [python]
-   repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        name: isort
        entry: isort
        types: [python]
        args: ["--profile", "black", "--filter-files"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
    -   id: mypy
        name: mypy
        entry: mypy
        types: [python]
        args: [--ignore-missing-imports]
        files: utils/|media_downloader.py
        exclude: tests/
-   repo: https://github.com/pycqa/pylint
    rev: v2.14.5
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args: [
          "-rn", # Only display messages
          "-sn", # Don't display the score
          "--rcfile=pylintrc" # Link to your config file
        ]
        files: utils/|media_downloader.py
        exclude: tests/
