coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch: yes

comment:
  require_changes: true