name: Unittest

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '3.6', '3.7', '3.8']
    name: Test - Python ${{ matrix.python-version }} on ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: make deps
    - name: Code Check - Pylint
      run: make pylint
    - name: Static Type Check - Mypy
      run: make static_type_check
    - name: Test with pytest
      run: make test